// src/components/MainPageHero/MainPageHero.svelte
<script>
  import Greetings from "./Greetings.svelte";
</script>

<div
  className="hero min-h-screen"
  style={{
    backgroundImage:
      "url(https://img.daisyui.com/images/stock/photo-1507358522600-9f71e620c44e.webp)",
  }}
>
  <div className="hero-overlay"></div>
  <div className="hero-content text-neutral-content text-center">
    <Greetings />
  </div>
</div>

// src/components/MainPageHero/MainPageHero.tsx
import Greetings from "./Greetings";

export default function MainPageHero() {
  return (
    <div
      className="hero min-h-screen"
      style={{
        backgroundImage:
          "url(https://img.daisyui.com/images/stock/photo-1507358522600-9f71e620c44e.webp)",
      }}
    >
      <div className="hero-overlay"></div>
      <div className="hero-content text-neutral-content text-center">
        <Greetings />
      </div>
    </div>
  );
}
