// src/components/Header/NavBarEnd.svelte
<script>
  import ThemeDropdown from "./ThemeDropdown.svelte";
</script>

<div className="navbar-end">
  <button className="btn btn-ghost btn-circle">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
      />
    </svg>
  </button>
  <ThemeDropdown />
</div>

// src/components/Header/NavBarEnd.tsx
import ThemeDropdown from "./ThemeDropdown";

export default function NavBarEnd() {
    return (
        <div className="navbar-end">
            <button className="btn btn-ghost btn-circle">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /> </svg>
            </button>
            <ThemeDropdown />
        </div>
    )
}
